// Auto-generated API client for jsonplaceholder.typicode.com
// Generated by Unbrowse

const BASE_URL = "https://jsonplaceholder.typicode.com";

interface RequestOptions {
  headers?: Record<string, string>;
}

function getAuthHeaders(): Record<string, string> {
  return {};
}

export async function getPosts(options?: RequestOptions): Promise<unknown> {
  const res = await fetch(`${BASE_URL}/posts`, {
    method: "GET",
    headers: { ...getAuthHeaders(), ...options?.headers },
  });
  return res.json();
}

export async function getPosts(id: string, options?: RequestOptions): Promise<unknown> {
  const res = await fetch(`${BASE_URL}/posts/${id}`, {
    method: "GET",
    headers: { ...getAuthHeaders(), ...options?.headers },
  });
  return res.json();
}

export async function postPosts(options?: RequestOptions): Promise<unknown> {
  const res = await fetch(`${BASE_URL}/posts`, {
    method: "POST",
    headers: { ...getAuthHeaders(), ...options?.headers },
  });
  return res.json();
}

export async function getUsers(options?: RequestOptions): Promise<unknown> {
  const res = await fetch(`${BASE_URL}/users`, {
    method: "GET",
    headers: { ...getAuthHeaders(), ...options?.headers },
  });
  return res.json();
}

export async function getComments(options?: RequestOptions): Promise<unknown> {
  const res = await fetch(`${BASE_URL}/comments`, {
    method: "GET",
    headers: { ...getAuthHeaders(), ...options?.headers },
  });
  return res.json();
}

export async function putPosts(id: string, options?: RequestOptions): Promise<unknown> {
  const res = await fetch(`${BASE_URL}/posts/${id}`, {
    method: "PUT",
    headers: { ...getAuthHeaders(), ...options?.headers },
  });
  return res.json();
}

export async function deletePosts(id: string, options?: RequestOptions): Promise<unknown> {
  const res = await fetch(`${BASE_URL}/posts/${id}`, {
    method: "DELETE",
    headers: { ...getAuthHeaders(), ...options?.headers },
  });
  return res.json();
}

export async function getPostsComments(id: string, options?: RequestOptions): Promise<unknown> {
  const res = await fetch(`${BASE_URL}/posts/${id}/comments`, {
    method: "GET",
    headers: { ...getAuthHeaders(), ...options?.headers },
  });
  return res.json();
}
