// Auto-generated API client for api.test.com
// Generated by Unbrowse

const BASE_URL = "https://api.test.com";

interface RequestOptions {
  headers?: Record<string, string>;
}

function getAuthHeaders(): Record<string, string> {
  const token = process.env.API_TOKEN ?? "";
  return { Authorization: `Bearer ${token}` };
}

export async function getUsers(options?: RequestOptions): Promise<unknown> {
  const res = await fetch(`${BASE_URL}/users`, {
    method: "GET",
    headers: { ...getAuthHeaders(), ...options?.headers },
  });
  return res.json();
}

export async function getUsers(id: string, options?: RequestOptions): Promise<unknown> {
  const res = await fetch(`${BASE_URL}/users/${id}`, {
    method: "GET",
    headers: { ...getAuthHeaders(), ...options?.headers },
  });
  return res.json();
}

export async function postPosts(options?: RequestOptions): Promise<unknown> {
  const res = await fetch(`${BASE_URL}/posts`, {
    method: "POST",
    headers: { ...getAuthHeaders(), ...options?.headers },
  });
  return res.json();
}
