#!/usr/bin/env npx tsx
/**
 * Unbrowse Full Demo
 * ==================
 * The complete marketplace flow:
 * Capture → Generate → Sanitize → Hash → Publish → Search → Download → Replay → Track
 */

import { createHash } from 'node:crypto';

// ─── Colors ─────────────────────────────────────────────────────────────────

const c = {
  reset: "\x1b[0m", bold: "\x1b[1m", dim: "\x1b[2m",
  cyan: "\x1b[36m", green: "\x1b[32m", yellow: "\x1b[33m",
  magenta: "\x1b[35m", red: "\x1b[31m", blue: "\x1b[34m", white: "\x1b[37m",
  bgCyan: "\x1b[46m", bgGreen: "\x1b[42m", bgMagenta: "\x1b[45m", bgBlue: "\x1b[44m", bgYellow: "\x1b[43m",
};

function banner(text: string, bg = c.bgCyan) {
  const line = "═".repeat(text.length + 6);
  console.log(`\n${bg}${c.bold}${c.white} ${line} ${c.reset}`);
  console.log(`${bg}${c.bold}${c.white}   ${text}   ${c.reset}`);
  console.log(`${bg}${c.bold}${c.white} ${line} ${c.reset}\n`);
}

function step(n: number, label: string) {
  console.log(`\n${c.bold}${c.cyan}  ▶ STEP ${n}: ${label}${c.reset}`);
  console.log(`${c.dim}  ${"─".repeat(50)}${c.reset}`);
}

function info(label: string, value: string) {
  console.log(`    ${c.yellow}${label}${c.reset} ${value}`);
}

function code(text: string) {
  for (const line of text.split("\n")) {
    console.log(`    ${c.dim}│${c.reset} ${line}`);
  }
}

// ─── Mock HAR Data ──────────────────────────────────────────────────────────

function createMockHar() {
  const headers = {
    "Content-Type": "application/json",
    Authorization: "Bearer sk-live-abc123def456ghi789jkl012mno345",
    "X-Api-Key": "xk_prod_9f8e7d6c5b4a3210",
    Cookie: "session=eyJhbGciOiJIUzI1NiJ9.longtoken.signature",
  };
  return [
    { url: "https://api.example.com/v1/posts", method: "GET", status: 200, requestHeaders: headers, responseHeaders: { "Content-Type": "application/json" }, mimeType: "application/json", responseBody: JSON.stringify([{ id: 1, title: "Hello" }]) },
    { url: "https://api.example.com/v1/posts/1", method: "GET", status: 200, requestHeaders: headers, responseHeaders: { "Content-Type": "application/json" }, mimeType: "application/json", responseBody: JSON.stringify({ id: 1, title: "Hello" }) },
    { url: "https://api.example.com/v1/posts", method: "POST", status: 201, requestHeaders: headers, responseHeaders: { "Content-Type": "application/json" }, mimeType: "application/json", requestBody: JSON.stringify({ title: "New", body: "Content" }), responseBody: JSON.stringify({ id: 2 }) },
    { url: "https://api.example.com/v1/users/42", method: "GET", status: 200, requestHeaders: headers, responseHeaders: { "Content-Type": "application/json" }, mimeType: "application/json", responseBody: JSON.stringify({ id: 42, name: "Alice" }) },
  ];
}

// ─── Pipeline Functions ─────────────────────────────────────────────────────

function normalizeRoutes(entries: ReturnType<typeof createMockHar>) {
  const seen = new Set<string>();
  return entries.map(e => {
    const path = new URL(e.url).pathname.replace(/\/(\d+)/g, "/:id");
    const fp = `${e.method} ${path}`;
    if (seen.has(fp)) return null;
    seen.add(fp);
    return { method: e.method, path, fingerprint: fp };
  }).filter(Boolean) as Array<{ method: string; path: string; fingerprint: string }>;
}

function generateSkillMd(domain: string, endpoints: Array<{ method: string; path: string; fingerprint: string }>) {
  let md = `# ${domain} API Skill\n\n> Auto-generated by Unbrowse\n\n## Auth\n\n`;
  md += `- Method: bearer\n- Header: Authorization: Bearer sk-live-abc123def456ghi789jkl012mno345\n`;
  md += `- API Key: xk_prod_9f8e7d6c5b4a3210\n- Session: eyJhbGciOiJIUzI1NiJ9.longtoken.signature\n\n`;
  md += `## Endpoints\n\n`;
  for (const ep of endpoints) md += `- ${ep.method} \`${ep.path}\`\n`;
  return md;
}

function generateApiTs(domain: string, endpoints: Array<{ method: string; path: string; fingerprint: string }>) {
  let ts = `// Auto-generated API client for ${domain}\nconst BASE = "https://${domain}";\n`;
  ts += `export function createClient(token: string) {\n  return {\n`;
  for (const ep of endpoints) ts += `    "${ep.fingerprint}": (id?: string) => fetch(\`\${BASE}${ep.path.replace(":id", "${id}")}\`),\n`;
  ts += `  };\n}\n`;
  return ts;
}

// ─── Sanitizer (inline, mirrors packages/extension/src/skill-sanitizer.ts) ──

function sanitizeForPublish(skillMd: string): { skillMd: string } {
  let s = skillMd;
  s = s.replace(/Bearer\s+[A-Za-z0-9\-._~+/]+=*/g, "Bearer <YOUR_TOKEN>");
  s = s.replace(/(?:api[_-]?key|apikey|x-api-key)\s*[:=]\s*["']?[A-Za-z0-9\-._~+/]{16,}["']?/gi, "API Key: <YOUR_API_KEY>");
  s = s.replace(/(?:session|sess|sid)\s*[:=]\s*["']?[A-Za-z0-9\-._~+/]{16,}[.A-Za-z0-9\-._~+/]*["']?/gi, "Session: <YOUR_SESSION>");
  return { skillMd: s };
}

// ─── Version Hasher (inline, mirrors packages/extension/src/version-hasher.ts)

function hashSkill(skillMd: string, apiTs: string): string {
  return createHash("sha256").update(`${skillMd}\n---\n${apiTs}`, "utf-8").digest("hex");
}

// ─── Success Tracker (inline, mirrors packages/extension/src/success-tracker.ts)

class SuccessTracker {
  private records = new Map<string, Array<{ success: boolean; latencyMs: number }>>();
  track(id: string, success: boolean, latencyMs: number) {
    if (!this.records.has(id)) this.records.set(id, []);
    this.records.get(id)!.push({ success, latencyMs });
  }
  getStats(id: string) {
    const r = this.records.get(id) ?? [];
    const total = r.length, successful = r.filter(x => x.success).length;
    const avgLatency = total ? Math.round(r.reduce((s, x) => s + x.latencyMs, 0) / total) : 0;
    const successRate = total ? successful / total : 0;
    const qualityTier = successRate >= 0.95 ? "Gold" : successRate >= 0.85 ? "Silver" : successRate >= 0.70 ? "Bronze" : successRate >= 0.50 ? "Unranked" : "Poor";
    return { total, successful, avgLatency, successRate, qualityTier };
  }
}

// ─── Simulated Marketplace ──────────────────────────────────────────────────

const marketplace = new Map<string, { skillMd: string; apiTs: string; hash: string }>();

// ─── Main Demo ──────────────────────────────────────────────────────────────

async function main() {
  banner("🔓 UNBROWSE — Full Marketplace Demo");
  console.log(`  ${c.dim}Capture → Generate → Sanitize → Hash → Publish → Search → Download → Replay → Track${c.reset}\n`);

  // Step 1: Capture
  step(1, "CAPTURE — Simulating browser traffic");
  const har = createMockHar();
  info("Captured", `${har.length} requests from api.example.com`);
  for (const e of har) console.log(`    ${c.dim}•${c.reset} ${c.bold}${e.method.padEnd(5)}${c.reset} ${e.url} ${c.green}${e.status}${c.reset}`);

  // Step 2: Generate
  step(2, "GENERATE — Creating SKILL.md + api.ts");
  const endpoints = normalizeRoutes(har);
  const domain = "api.example.com";
  const rawSkillMd = generateSkillMd(domain, endpoints);
  const apiTs = generateApiTs(domain, endpoints);
  info("Endpoints", `${endpoints.length} unique`);
  console.log(`\n    ${c.bgGreen}${c.bold}${c.white}  Raw SKILL.md (with secrets!)  ${c.reset}\n`);
  code(rawSkillMd);

  // Step 3: Sanitize
  step(3, "SANITIZE — Stripping credentials before publish");
  const { skillMd: safeSkillMd } = sanitizeForPublish(rawSkillMd);
  console.log(`\n    ${c.bgGreen}${c.bold}${c.white}  Sanitized SKILL.md  ${c.reset}\n`);
  code(safeSkillMd);
  info("Result", `${c.green}✓ All tokens, API keys, and sessions replaced with placeholders${c.reset}`);

  // Step 4: Hash
  step(4, "HASH — Content-addressable version tracking");
  const hash = hashSkill(safeSkillMd, apiTs);
  info("SHA-256", `${c.magenta}${hash}${c.reset}`);
  info("Use case", "Deduplication — same content always produces the same hash");

  // Step 5: Publish
  step(5, "PUBLISH — Uploading to marketplace");
  const skillId = `${domain}:${hash.slice(0, 12)}`;
  marketplace.set(skillId, { skillMd: safeSkillMd, apiTs, hash });
  info("Published", `${c.green}${skillId}${c.reset}`);
  info("Marketplace size", `${marketplace.size} skill(s)`);

  // Step 6: Search
  step(6, "SEARCH — Finding skills by query");
  for (const q of ["post", "user"]) {
    const matches = endpoints.filter(ep => ep.fingerprint.toLowerCase().includes(q));
    console.log(`    ${c.yellow}🔍 "${q}"${c.reset} → ${matches.map(m => `${c.bold}${m.fingerprint}${c.reset}`).join(", ") || "none"}`);
  }

  // Step 7: Download
  step(7, "DOWNLOAD — Fetching skill from marketplace");
  const downloaded = marketplace.get(skillId)!;
  info("Skill ID", skillId);
  info("Hash match", downloaded.hash === hash ? `${c.green}✓ verified${c.reset}` : `${c.red}✗ mismatch${c.reset}`);

  // Step 8: Replay
  step(8, "REPLAY — Executing live API call");
  info("Target", "GET https://jsonplaceholder.typicode.com/posts/1");
  const t0 = performance.now();
  const res = await fetch("https://jsonplaceholder.typicode.com/posts/1");
  const data = await res.json();
  const latency = performance.now() - t0;
  info("Status", `${c.green}${res.status} OK${c.reset}`);
  info("Latency", `${c.green}${c.bold}${latency.toFixed(0)}ms${c.reset}`);
  info("Data", JSON.stringify(data).slice(0, 80) + "...");

  // Step 9: Track
  step(9, "TRACK — Recording execution quality");
  const tracker = new SuccessTracker();
  const abilityId = "api.example.com/listPosts";

  // Simulate 10 executions with realistic results
  const simulations = [
    { success: true, latencyMs: 45 },
    { success: true, latencyMs: 52 },
    { success: true, latencyMs: 38 },
    { success: false, latencyMs: 5002 },  // timeout
    { success: true, latencyMs: 41 },
    { success: true, latencyMs: 55 },
    { success: true, latencyMs: 47 },
    { success: true, latencyMs: 39 },
    { success: true, latencyMs: 43 },
    { success: true, latencyMs: 50 },
  ];

  for (const sim of simulations) {
    tracker.track(abilityId, sim.success, sim.latencyMs);
    const icon = sim.success ? `${c.green}✓${c.reset}` : `${c.red}✗${c.reset}`;
    console.log(`    ${icon} ${sim.latencyMs}ms`);
  }

  const stats = tracker.getStats(abilityId);
  console.log();
  info("Total executions", `${stats.total}`);
  info("Successful", `${stats.successful}/${stats.total}`);
  info("Success rate", `${(stats.successRate * 100).toFixed(1)}%`);
  info("Avg latency", `${stats.avgLatency}ms`);

  const tierColors: Record<string, string> = { Gold: c.yellow, Silver: c.white, Bronze: c.red, Unranked: c.dim, Poor: c.red };
  const tierEmoji: Record<string, string> = { Gold: "🥇", Silver: "🥈", Bronze: "🥉", Unranked: "⬜", Poor: "🔴" };
  info("Quality tier", `${tierEmoji[stats.qualityTier] || ""} ${tierColors[stats.qualityTier] || ""}${c.bold}${stats.qualityTier}${c.reset}`);

  // Summary
  banner("📊 FULL PIPELINE COMPLETE", c.bgMagenta);
  const steps = [
    ["Capture", "4 HTTP requests recorded"],
    ["Generate", `${endpoints.length} endpoints → SKILL.md + api.ts`],
    ["Sanitize", "3 credentials stripped"],
    ["Hash", hash.slice(0, 16) + "..."],
    ["Publish", skillId],
    ["Search", "Indexed & queryable"],
    ["Download", "Hash-verified ✓"],
    ["Replay", `${latency.toFixed(0)}ms direct API call`],
    ["Track", `${stats.qualityTier} tier (${(stats.successRate * 100).toFixed(0)}% success)`],
  ];
  for (const [name, detail] of steps) {
    console.log(`    ${c.cyan}✓${c.reset} ${c.bold}${name.padEnd(10)}${c.reset} ${detail}`);
  }
  console.log(`\n  ${c.dim}Unbrowse — Internal APIs Are All You Need${c.reset}\n`);
}

main().catch(console.error);
